server:
  port: @appPort@
eureka:
  ###--close self preseration and clean the down server every 20s
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 20000
  instance:
    metadata-map:
      zone: @eurekaZone@
    #hostname: @eurekaHostName@
    prefer-ip-address: true
    ip-address: @eurekaHostIP@
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: @eurekaServer@
spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka
      password: eureka


