server:
  port: 8020

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:eureka@10.1.1.227:8761/eureka/

spring:
  application:
    name: webapp-sidecar

###----the health must return json->staus:UP
###----access the sidecar from zuul gateway
sidecar:
  port: 8000
  health-uri: http://10.1.3.151:8000/sidecar/health