server:
  port: 8081
eureka:
  instance:
    metadata-map:
      zone: zone1
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/
spring:
  application:
    name: webapp-server
