spring:
  redis:
    host: 10.1.1.222
    port: 6379
    password:
    database: 14
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 100
  rabbitmq:
    host: 10.1.1.222
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        max-concurrency: 10