server:
  port: 8090
eureka:
  instance:
    metadata-map:
      zone: zone1
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lljuser/spring-cloud-config-center.git
          #username: llj
          #password: lljlljllj
#        health:
#          repositories:
#            webapp-server:
#              name: webapp-server
#              label: master
#              profiles: dev
    bus:
      enabled: true
  security:
    user:
      name: config
      password: config
      roles: ENDPOINT_ADMIN
  rabbitmq:
    host: 10.1.1.222
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        max-concurrency: 10
###encrypt some config info
encrypt:
  key: thisismykey

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.cloud.config.server.config.ConfigServerHealthIndicator: DEBUG


