server:
  port: @appPort@
eureka:
  instance:
    metadata-map:
      zone: @eurekaZone@
    prefer-ip-address: true
    ip-address: @eurekaHostIP@
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: @eurekaServer@

spring:
  profiles:
    active: @appEnv@
  application:
    name: config-server
  cloud:
#    inetutils:
#      preferred-networks:
#        - 10.1
    config:
      server:
        git:
          uri: https://github.com/lljuser/spring-cloud-config-center.git
          #username: llj
          #password: lljlljllj
#        health:
#          repositories:
#            webapp-server:
#              name: webapp-server
#              label: master
#              profiles: dev
    bus:
      enabled: true
  security:
    user:
      name: config
      password: config
      roles: ENDPOINT_ADMIN

###encrypt some config info
encrypt:
  key: thisismykey

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.cloud.config.server.config.ConfigServerHealthIndicator: DEBUG


