server:
  port: @appPort@

spring:
  application:
    name: hystrix-turbine
eureka:
  instance:
    prefer-ip-address: true
    ip-address: @eurekaHostIP@
    metadata-map:
      zone: @eurekaZone@
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: @eurekaServer@


management:
  endpoints:
    web:
      exposure:
        include: "*"
turbine:
  app-config: zuul-server,webapp
  cluster-name-expression: "'default'"
  combine-host-port: true